# Generated by Django 5.2 on 2025-04-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='temp_trigger',
        ),
    ]
